# Generated by Django 5.0.9 on 2025-06-22 09:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_almacen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clie', models.CharField(blank=True, max_length=255)),
                ('apellido_clie', models.CharField(blank=True, max_length=255, null=True)),
                ('dni_cliente', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('ruc_cliente', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('direccion_clie', models.CharField(blank=True, max_length=255, null=True)),
                ('razon_socialCliente', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator()])),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tb_cliente',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_formaPago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cuota', models.IntegerField(default=0)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_forma_pago',
            },
        ),
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id_legend', models.AutoField(primary_key=True, serialize=False)),
                ('legend_code', models.CharField(max_length=4)),
                ('legend_value', models.TextField()),
            ],
            options={
                'db_table': 'tb_legend',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('telf_suc', models.CharField(max_length=20)),
                ('correo_suc', models.CharField(max_length=150)),
                ('direccion_sucursal', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_sucursal',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(max_length=4)),
                ('tipo_doc', models.CharField(max_length=4)),
                ('numero_serie', models.CharField(max_length=4)),
                ('correlativo', models.CharField(max_length=25)),
                ('tipo_moneda', models.CharField(max_length=3)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('hora_emision', models.TimeField(auto_now_add=True)),
                ('empresa_ruc', models.CharField(max_length=11)),
                ('razon_social', models.CharField(max_length=50)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('urbanizacion', models.CharField(blank=True, max_length=200, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('email_empresa', models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator()])),
                ('telefono_emp', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_tipo_doc', models.CharField(max_length=11)),
                ('monto_Oper_Gravadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('monto_Igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('valor_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('sub_Total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('monto_Imp_Venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('estado_Documento', models.CharField(default='0', max_length=1)),
                ('manual', models.BooleanField(default=False)),
                ('pdf_url', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_venta.cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forma_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_venta.formapago')),
                ('legend_comprobante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_venta.legend')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_venta.sucursal')),
            ],
            options={
                'db_table': 'tb_comprobante',
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id_detalleComprobante', models.AutoField(primary_key=True, serialize=False)),
                ('unidad', models.CharField(max_length=6)),
                ('cantidad', models.PositiveIntegerField()),
                ('id_producto', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_valorUnitario', models.FloatField(default=0)),
                ('igv_detalle', models.FloatField(default=0)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('hora_emision', models.TimeField(auto_now_add=True)),
                ('monto_Precio_Unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_Valor_Venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comprobante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='gestion_venta.comprobante')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_almacen.producto')),
            ],
            options={
                'db_table': 'tb_detalle_comprobante',
            },
        ),
    ]
