# Generated by Django 5.1.1 on 2024-10-23 00:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_almacen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clie', models.CharField(blank=True, max_length=255)),
                ('apellido_clie', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_clie', models.CharField(blank=True, max_length=255, null=True)),
                ('ruc_cliente', models.CharField(blank=True, max_length=11, null=True)),
                ('razon_socialCliente', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator()])),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tb_cliente',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('ruc_empresa', models.CharField(blank=True, max_length=11)),
                ('razon_social', models.CharField(max_length=50)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_empresa', models.CharField(max_length=100, null=True)),
                ('ubigeo', models.CharField(blank=True, max_length=100, null=True)),
                ('urbanizacion', models.CharField(blank=True, max_length=200, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('email_empresa', models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator()])),
                ('telefono_emp', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_empresa',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_formaPago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota', models.IntegerField()),
                ('fecha_pago', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_forma_pago',
            },
        ),
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id_legend', models.AutoField(primary_key=True, serialize=False)),
                ('legend_code', models.CharField(max_length=4)),
                ('legend_value', models.TextField()),
            ],
            options={
                'db_table': 'tb_legend',
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id_detalleComprobante', models.AutoField(primary_key=True, serialize=False)),
                ('unidad', models.CharField(max_length=6)),
                ('cantidad', models.PositiveIntegerField()),
                ('cod_producto', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_valorUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igv_detalle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('hora_emision', models.TimeField(auto_now_add=True)),
                ('total_Impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_Precio_Unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_Valor_Venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_almacen.producto')),
            ],
            options={
                'db_table': 'tb_detalle_comprobante',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('uuid_comprobante', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipo_operacion', models.CharField(max_length=4)),
                ('tipo_doc', models.CharField(max_length=3)),
                ('numero_serie', models.CharField(max_length=4)),
                ('correlativo', models.CharField(max_length=10)),
                ('tipo_moneda', models.CharField(max_length=3)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('hora_emision', models.TimeField(auto_now_add=True)),
                ('empresa_ruc', models.CharField(max_length=11)),
                ('cliente_tipo_doc', models.CharField(max_length=11)),
                ('cliente_num_doc', models.CharField(max_length=11)),
                ('cliente_razon_social', models.CharField(max_length=255)),
                ('cliente_direccion', models.TextField(max_length=255)),
                ('monto_Oper_Gravadas', models.FloatField(default=0.0)),
                ('monto_Igv', models.FloatField(default=0.0)),
                ('valor_venta', models.FloatField(default=0.0)),
                ('total_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_Total', models.FloatField(default=0.0)),
                ('monto_Imp_Venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado_Documento', models.CharField(default='0', max_length=1)),
                ('manual', models.BooleanField(default=False)),
                ('receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_venta.cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_venta.detallecomprobante')),
                ('emisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_venta.empresa')),
                ('forma_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_venta.formapago')),
                ('legend_comprobante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_venta.legend')),
            ],
            options={
                'db_table': 'tb_comprobante',
            },
        ),
    ]
