# Generated by Django 5.1.1 on 2024-10-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_tipo_doc',
            field=models.CharField(max_length=3),
        ),
    ]
