# Generated by Django 5.1.1 on 2024-11-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='tipo_doc',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
