# Generated by Django 5.1.1 on 2024-10-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='tipo_empresa',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='ubigeo',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='telefono_emp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='correlativo',
            field=models.CharField(max_length=25),
        ),
    ]
