# Generated by Django 5.1.1 on 2024-10-26 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecomprobante',
            name='comprobante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='gestion_venta.comprobante'),
        ),
    ]
