# Generated by Django 5.1.1 on 2024-10-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_venta', '0002_alter_cliente_cliente_tipo_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_numDoc',
            new_name='ruc_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni_cliente',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
