# Generated by Django 5.1.1 on 2024-10-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_venta', '0002_remove_comprobante_tipo_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='total_impuestos',
        ),
        migrations.RemoveField(
            model_name='detallecomprobante',
            name='total_Impuestos',
        ),
    ]
