# Generated by Django 5.1.1 on 2024-10-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_venta', '0003_remove_comprobante_total_impuestos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobante',
            old_name='pdf_venta',
            new_name='pdf_url',
        ),
    ]
