# Generated by Django 5.1.1 on 2024-10-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_venta', '0003_rename_cliente_numdoc_cliente_ruc_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_tipo_doc',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
