# Generated by Django 5.1.1 on 2024-10-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_venta', '0003_alter_comprobante_monto_igv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecomprobante',
            name='monto_Precio_Unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallecomprobante',
            name='monto_Valor_Venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallecomprobante',
            name='total_Impuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
