# Generated by Django 5.1.1 on 2024-10-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_venta', '0004_alter_detallecomprobante_monto_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
