# Generated by Django 5.1.1 on 2024-10-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_venta', '0004_alter_cliente_cliente_tipo_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_tipo_doc',
        ),
    ]
