# Generated by Django 5.1.1 on 2024-11-02 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
