# Generated by Django 5.1.1 on 2024-09-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_permission', models.CharField(max_length=50, unique=True)),
                ('role', models.ManyToManyField(related_name='permissions', to='authentication.role')),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileType',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
