# Generated by Django 5.1.1 on 2024-10-01 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_role_remove_profile_profile_type_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Rol',
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
