# Generated by Django 5.0.9 on 2024-11-13 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_almacen', '0001_initial'),
        ('gestion_venta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('codigo_au', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_au', models.CharField(max_length=50)),
                ('tabla', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=20)),
                ('registro', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'Auditoria',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id_tipoMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_tipoMovimiento',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=50, null=True)),
                ('cant_total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_venta.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.tipomovimiento')),
            ],
            options={
                'db_table': 'tb_movimiento',
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id_detalleMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('detalleComprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_venta.detallecomprobante')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_almacen.producto')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.movimiento')),
            ],
            options={
                'db_table': 'tb_detalleMovimiento',
            },
        ),
    ]
