# Generated by Django 5.1.1 on 2024-10-31 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_venta', '0001_initial'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='detalleComprobante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_venta.detallecomprobante'),
        ),
    ]
